"""Known settings.json keys — used by doctor/sync to merge templates into local config."""

from __future__ import annotations

# Keys the scanner reads (keep in sync with ScannerConfig.from_file).
KNOWN_SETTINGS_KEYS: tuple[str, ...] = (
    "dry_run",
    "network",
    "strategy",
    "min_apr",
    "apr_field",
    "pool_sort_field",
    "raydium_api_base",
    "pool_type",
    "sort_type",
    "page_size",
    "pages",
    "http_timeout_seconds",
    "page_delay_seconds",
    "min_liquidity_usd",
    "hard_exit_min_tvl_usd",
    "min_volume_24h_usd",
    "max_position_usd",
    "max_pool_age_hours",
    "min_pool_age_hours",
    "min_burn_percent",
    "allowed_quote_symbols",
    "blocked_token_symbols",
    "blocked_mints",
    "require_pool_id",
    "require_verified_raydium_pool",
    "verify_pool_on_chain",
    "verify_pool_raydium_api",
    "require_sell_route",
    "route_sources",
    "max_route_price_impact_pct",
    "write_rejections",
    "rejections_csv_path",
    "use_robust_routing",
    "track_liquidity_health",
    "liquidity_history_path",
    "emergency_close_enabled",
    "emergency_alerts_path",
    "emergency_base_symbol",
    "emergency_max_slippage_pct",
    "position_size_sol",
    "reserve_sol",
    "dashboard_path",
    "solana_rpc_urls",
    "momentum_enabled",
    "min_momentum_score",
    "require_momentum_score",
    "momentum_hold_hours",
    "momentum_min_volume_tvl_ratio",
    "momentum_sweet_min_pool_age_hours",
    "momentum_sweet_max_pool_age_hours",
    "momentum_min_tvl_usd",
    "momentum_top_hot",
    "momentum_detective_enabled",
    "momentum_probe_market_lists",
    "sort_candidates_by_momentum",
)
